// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ratchet.proto

/*
Package ratchet is a generated protocol buffer package.

It is generated from these files:
	ratchet.proto

It has these top-level messages:
	SignalRequest
	SignalReply
*/
package ratchet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignalRequest struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *SignalRequest) Reset()                    { *m = SignalRequest{} }
func (m *SignalRequest) String() string            { return proto.CompactTextString(m) }
func (*SignalRequest) ProtoMessage()               {}
func (*SignalRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SignalRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SignalReply struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *SignalReply) Reset()                    { *m = SignalReply{} }
func (m *SignalReply) String() string            { return proto.CompactTextString(m) }
func (*SignalReply) ProtoMessage()               {}
func (*SignalReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SignalReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*SignalRequest)(nil), "ratchet.SignalRequest")
	proto.RegisterType((*SignalReply)(nil), "ratchet.SignalReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Node service

type NodeClient interface {
	Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalReply, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalReply, error) {
	out := new(SignalReply)
	err := grpc.Invoke(ctx, "/ratchet.Node/Signal", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	Signal(context.Context, *SignalRequest) (*SignalReply, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ratchet.Node/Signal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Signal(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ratchet.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signal",
			Handler:    _Node_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ratchet.proto",
}

func init() { proto.RegisterFile("ratchet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0x2c, 0x49,
	0xce, 0x48, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x94, 0xb9,
	0x78, 0x83, 0x33, 0xd3, 0xf3, 0x12, 0x73, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84,
	0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25,
	0x79, 0x2e, 0x6e, 0x98, 0xa2, 0x82, 0x9c, 0x4a, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0xa8,
	0x0a, 0x10, 0xd3, 0xc8, 0x81, 0x8b, 0xc5, 0x2f, 0x3f, 0x25, 0x55, 0xc8, 0x82, 0x8b, 0x0d, 0xa2,
	0x50, 0x48, 0x4c, 0x0f, 0x66, 0x21, 0x8a, 0xf1, 0x52, 0x22, 0x18, 0xe2, 0x05, 0x39, 0x95, 0x4a,
	0x0c, 0x4e, 0x5a, 0x5c, 0x12, 0xf9, 0x29, 0x99, 0x79, 0xc5, 0x05, 0x39, 0x89, 0xc5, 0xb9, 0x89,
	0x45, 0x99, 0x69, 0x39, 0xa9, 0x30, 0x95, 0x4e, 0x3c, 0x41, 0x10, 0x46, 0x00, 0xc8, 0xe9, 0x01,
	0x8c, 0x49, 0x6c, 0x60, 0x3f, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x75, 0xd2, 0x71, 0x36,
	0xd4, 0x00, 0x00, 0x00,
}
